#
# Cross-compile release artifacts for multiple CPU architectures
#
FROM rust:latest AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc-arm-linux-gnueabihf \
    libc6-dev-armhf-cross \
    libgcc-12-dev-armhf-cross \
    musl-tools \
    pkg-config \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/*

RUN rustup target add \
    armv7-unknown-linux-gnueabihf \
    x86_64-unknown-linux-musl

ENV PKG_CONFIG_ALLOW_CROSS=1 \
    CC_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc \
    CXX_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-g++ \
    AR_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-ar \
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc \
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_AR=arm-linux-gnueabihf-ar \
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_RUSTFLAGS="-C target-feature=+crt-static" \
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=musl-gcc

WORKDIR /phantun
COPY . .

RUN cargo build --release --target armv7-unknown-linux-gnueabihf \
  && cargo build --release --target x86_64-unknown-linux-musl \
  && mkdir -p /out/armv7-unknown-linux-gnueabihf /out/x86_64-unknown-linux-musl \
  && install -m 755 target/armv7-unknown-linux-gnueabihf/release/server /out/armv7-unknown-linux-gnueabihf/phantun-server \
  && install -m 755 target/armv7-unknown-linux-gnueabihf/release/client /out/armv7-unknown-linux-gnueabihf/phantun-client \
  && install -m 755 target/x86_64-unknown-linux-musl/release/server /out/x86_64-unknown-linux-musl/phantun-server \
  && install -m 755 target/x86_64-unknown-linux-musl/release/client /out/x86_64-unknown-linux-musl/phantun-client \
  && tar -C /out -czf /out/phantun_armv7-unknown-linux-gnueabihf.tar.gz armv7-unknown-linux-gnueabihf \
  && tar -C /out -czf /out/phantun_x64_musl.tar.gz x86_64-unknown-linux-musl

FROM scratch AS export

COPY --from=builder /out/phantun_armv7-unknown-linux-gnueabihf.tar.gz /
COPY --from=builder /out/phantun_x64_musl.tar.gz /
